### PR TITLE
Fixed minor tweaks to README:

### PR DESCRIPTION
**Pull request by Danpfeffer**
- removed md_document header
- updated call to autoplot.vector.points() to just autoplot()

@shk313 @timcdlucas

### CODE REVIEW

**Comment by timcdlucas** [comment]
Thanks @danpfeffer! One test failed which doesn't make much sense given minor tweaks to the readme. I've restarted that build in case it was just a server thing.

Otherwise I or someone will have to have a look.

**Comment by timcdlucas** [comment]
I guess we should get rid of the "## Warning: package 'malariaAtlas' was built under R version 3.4.4" stuff at the top of the readme. Just a 
```
```{r, echo = FALSE, message = FALSE, results = "hide"}
```
change to

```
```{r, echo = FALSE, message = FALSE, results = "hide", warning = FALSE}
```

should do it I think. I'll do it at some point if you don't fancy faffing.

**Comment by Danpfeffer** [comment]
> I guess we should get rid of the "## Warning: package 'malariaAtlas' was built under R version 3.4.4" stuff at the top of the readme. Just a
> 
> ```
> ```{r, echo = FALSE, message = FALSE, results = "hide"}
> ```
> change to
> 
> ```
> ```{r, echo = FALSE, message = FALSE, results = "hide", warning = FALSE}
> ```
> should do it I think. I'll do it at some point if you don't fancy faffing.

Ah man, that would be my bad!  Thanks for picking that up, will fix and merge myself.

**Comment by timcdlucas** [comment]
Great thanks!

**Comment by Danpfeffer** [comment]
np! shall I leave the tweaks branch around for now or delete?

**Comment by timcdlucas** [comment]
You can delete I think. All changes are merged.

**Pull request merged**
